import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import fs from "node:fs";
import path from "node:path";
import { defineConfig, type Plugin, type ViteDevServer } from "vite";


// =============================================================================
// Manus Debug Collector - Vite Plugin
// Writes browser logs directly to files, trimmed when exceeding size limit
// =============================================================================

const PROJECT_ROOT = import.meta.dirname;
const LOG_DIR = path.join(PROJECT_ROOT, ".manus-logs");
const MAX_LOG_SIZE_BYTES = 1 * 1024 * 1024; // 1MB per log file
const TRIM_TARGET_BYTES = Math.floor(MAX_LOG_SIZE_BYTES * 0.6); // Trim to 60% to avoid constant re-trimming

type LogSource = "browserConsole" | "networkRequests" | "sessionReplay";

function ensureLogDir() {
  if (!fs.existsSync(LOG_DIR)) {
    fs.mkdirSync(LOG_DIR, { recursive: true });
  }
}

function trimLogFile(logPath: string, maxSize: number) {
  try {
    if (!fs.existsSync(logPath) || fs.statSync(logPath).size <= maxSize) {
      return;
    }

    const lines = fs.readFileSync(logPath, "utf-8").split("\n");
    const keptLines: string[] = [];
    let keptBytes = 0;

    // Keep newest lines (from end) that fit within 60% of maxSize
    const targetSize = TRIM_TARGET_BYTES;
    for (let i = lines.length - 1; i >= 0; i--) {
      const lineBytes = Buffer.byteLength(`${lines[i]}\n`, "utf-8");
      if (keptBytes + lineBytes > targetSize) break;
      keptLines.unshift(lines[i]);
      keptBytes += lineBytes;
    }

    fs.writeFileSync(logPath, keptLines.join("\n"), "utf-8");
  } catch {
    /* ignore trim errors */
  }
}

function writeToLogFile(source: LogSource, entries: unknown[]) {
  if (entries.length === 0) return;

  ensureLogDir();
  const logPath = path.join(LOG_DIR, `${source}.log`);

  // Format entries with timestamps
  const lines = entries.map((entry) => {
    const ts = new Date().toISOString();
    return `[${ts}] ${JSON.stringify(entry)}`;
  });

  // Append to log file
  fs.appendFileSync(logPath, `${lines.join("\n")}\n`, "utf-8");

  // Trim if exceeds max size
  trimLogFile(logPath, MAX_LOG_SIZE_BYTES);
}

/**
 * Vite plugin to copy the pre-rendered static pages (generated by
 * scripts/generate-static-pages.mjs into /public) into the build output.
 *
 * This is what actually makes suburb/service pages have real, unique,
 * crawlable HTML instead of every route falling back to the one generic
 * SPA shell — critical for crawlers (including most AI crawlers) that
 * don't execute JavaScript. The root index.html is deliberately skipped
 * since that one must stay as Vite's real build output (it has the
 * script tag that boots the React app).
 */
function collectHtmlFiles(dir: string, acc: string[] = []): string[] {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const entryPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      collectHtmlFiles(entryPath, acc);
    } else if (entry.name.endsWith(".html")) {
      acc.push(entryPath);
    }
  }
  return acc;
}

function copyDirRecursive(src: string, dest: string, skipTopLevel: Set<string>, isTopLevel = true) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (isTopLevel && skipTopLevel.has(entry.name)) continue;
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, destPath, skipTopLevel, false);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

function vitePluginCopyStaticFiles(): Plugin {
  return {
    name: "copy-static-files",
    apply: "build",
    async writeBundle() {
      const sourceDir = path.join(PROJECT_ROOT, "public");
      const destDir = path.join(PROJECT_ROOT, "dist/public");
      // Anything added here must also be skipped by SKIP_TOP_LEVEL in
      // scripts/generate-known-paths.mjs. A file that is excluded here but
      // still listed in KNOWN_PATHS makes the worker serve the homepage at
      // HTTP 200 for that URL instead of a real 404.
      const skipTopLevel = new Set(["index.html"]);
      copyDirRecursive(sourceDir, destDir, skipTopLevel);

      // Pull the real built script/stylesheet tags out of Vite's own
      // index.html (hashed filenames are only known after this build) and
      // inject them into every copied static page, so the browser loads
      // the real app on top of the static content and React replaces it
      // with the full interactive site — same as how the homepage works.
      const builtIndexPath = path.join(destDir, "index.html");
      const builtIndexHtml = fs.readFileSync(builtIndexPath, "utf-8");
      const scriptTagMatch = builtIndexHtml.match(/<script type="module"[^>]*><\/script>/);
      const styleTagMatch = builtIndexHtml.match(/<link rel="stylesheet"[^>]*>/);
      const injectedTags = [scriptTagMatch?.[0], styleTagMatch?.[0]].filter(Boolean).join("\n  ");

      if (injectedTags) {
        for (const htmlFile of collectHtmlFiles(sourceDir).map((f) =>
          path.join(destDir, path.relative(sourceDir, f))
        )) {
          if (htmlFile === builtIndexPath) continue;
          const html = fs.readFileSync(htmlFile, "utf-8");
          fs.writeFileSync(htmlFile, html.replace("</head>", `  ${injectedTags}\n</head>`), "utf-8");
        }
      }

      console.log("Copied pre-rendered static pages to dist/public/");
    },
  };
}

/**
 * Vite plugin to collect browser debug logs
 * - POST /__manus__/logs: Browser sends logs, written directly to files
 * - Files: browserConsole.log, networkRequests.log, sessionReplay.log
 * - Auto-trimmed when exceeding 1MB (keeps newest entries)
 */
function vitePluginManusDebugCollector(): Plugin {
  return {
    name: "manus-debug-collector",

    transformIndexHtml(html) {
      if (process.env.NODE_ENV === "production") {
        return html;
      }
      return {
        html,
        tags: [
          {
            tag: "script",
            attrs: {
              src: "/__manus__/debug-collector.js",
              defer: true,
            },
            injectTo: "head",
          },
        ],
      };
    },

    configureServer(server: ViteDevServer) {
      // POST /__manus__/logs: Browser sends logs (written directly to files)
      server.middlewares.use("/__manus__/logs", (req, res, next) => {
        if (req.method !== "POST") {
          return next();
        }

        const handlePayload = (payload: any) => {
          // Write logs directly to files
          if (payload.consoleLogs?.length > 0) {
            writeToLogFile("browserConsole", payload.consoleLogs);
          }
          if (payload.networkRequests?.length > 0) {
            writeToLogFile("networkRequests", payload.networkRequests);
          }
          if (payload.sessionEvents?.length > 0) {
            writeToLogFile("sessionReplay", payload.sessionEvents);
          }

          res.writeHead(200, { "Content-Type": "application/json" });
          res.end(JSON.stringify({ success: true }));
        };

        const reqBody = (req as { body?: unknown }).body;
        if (reqBody && typeof reqBody === "object") {
          try {
            handlePayload(reqBody);
          } catch (e) {
            res.writeHead(400, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ success: false, error: String(e) }));
          }
          return;
        }

        let body = "";
        req.on("data", (chunk) => {
          body += chunk.toString();
        });

        req.on("end", () => {
          try {
            const payload = JSON.parse(body);
            handlePayload(payload);
          } catch (e) {
            res.writeHead(400, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ success: false, error: String(e) }));
          }
        });
      });
    },
  };
}

/**
 * Converts render-blocking <link rel="stylesheet"> into a non-blocking
 * preload+onload pattern so the browser can paint the hero sooner.
 * The noscript fallback keeps CSS working for crawlers.
 */
function vitePluginDeferCSS(): Plugin {
  return {
    name: "defer-css",
    apply: "build",
    transformIndexHtml: {
      order: "post",
      handler(html: string): string {
        return html.replace(
          /(<link\b[^>]*\brel="stylesheet"[^>]*>)/g,
          (match) => {
            const deferred = match.replace(
              /\brel="stylesheet"/,
              "rel=\"preload\" as=\"style\" onload=\"this.onload=null;this.rel='stylesheet'\""
            );
            return `${deferred}<noscript>${match}</noscript>`;
          }
        );
      },
    },
  };
}

const plugins = [react(), tailwindcss(), vitePluginCopyStaticFiles(), vitePluginManusDebugCollector(), vitePluginDeferCSS()];

export default defineConfig({
  plugins,
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "client", "src"),
      "@shared": path.resolve(import.meta.dirname, "shared"),
      "@assets": path.resolve(import.meta.dirname, "attached_assets"),
    },
  },
  envDir: path.resolve(import.meta.dirname),
  root: path.resolve(import.meta.dirname, "client"),
  build: {
    outDir: path.resolve(import.meta.dirname, "dist", "public"),
    emptyOutDir: true,
    // Performance optimizations
    minify: "terser",
    terserOptions: {
      compress: {
        drop_console: true,
        drop_debugger: true,
      },
    },
    rollupOptions: {
      output: {
        // FUNCTION form, not the object form — and the difference is the whole
        // point. See the history below before changing this.
        //
        // With the object form, Rollup assigns only the exact module ids listed.
        // "react" resolves to react/index.js, but React's actual implementation
        // lives in react/cjs/react.production.js, which is a *dependency* of
        // that id rather than the id itself. Unlisted dependencies fall to
        // Rollup's default assignment and land in whichever chunk reaches them
        // first — which was vendor-animation, via framer-motion. That is how
        // React core ended up inside the 128KB animation chunk while
        // vendor-react was a 3.6KB stub whose first line was
        // `import{r as t}from"./vendor-animation-*.js"`.
        //
        // Consequence measured on the deployed build (34e25ec): 120 of 142
        // chunks imported vendor-animation, and a suburb page shipped 43KB
        // brotli of framer-motion out of ~162KB total JS — roughly a quarter of
        // its payload — despite framer-motion being imported by exactly 11
        // source files, all of them service/blog/FAQ pages. Neither
        // SuburbPageTemplate nor Home imports it.
        //
        // Adding "react/jsx-runtime" to the object list was tried (7e7ff0e) and
        // proved completely inert: the revert produced a byte-identical
        // vendor-react (same hash, same 3634 bytes) across a build that
        // definitely re-ran. Do not try that again.
        //
        // The function is called for every module id, including the cjs
        // implementation files, so a path match catches what the object form
        // could not. React must be matched FIRST: framer-motion, the form
        // libraries and Radix all depend on it, and whichever chunk claims it
        // first is exactly how this went wrong.
        manualChunks(id) {
          if (!id.includes("node_modules")) return;
          // Matches both npm's flat layout and pnpm's
          // .pnpm/<pkg>@<ver>/node_modules/<pkg>/ nesting, since the trailing
          // /node_modules/<pkg>/ segment is present either way.
          if (/[\\/]node_modules[\\/](react|react-dom|scheduler)[\\/]/.test(id)) return "vendor-react";
          if (id.includes("framer-motion")) return "vendor-animation";
          if (/[\\/]node_modules[\\/](react-hook-form|@hookform[\\/]resolvers|zod)[\\/]/.test(id)) return "vendor-form";
          if (/[\\/]node_modules[\\/](clsx|tailwind-merge|nanoid)[\\/]/.test(id)) return "vendor-utils";
          // Everything else: Rollup's default. vendor-radix was deliberately
          // removed so each Radix package tree-shakes into only the chunks that
          // actually import it.
        },
      },
    },
    // Chunk size warnings
    chunkSizeWarningLimit: 500,
    // CSS code splitting
    cssCodeSplit: true,
    // Source maps for production debugging
    sourcemap: false,
    // Report compressed size
    reportCompressedSize: true,
  },
  server: {
    port: 3000,
    strictPort: false, // Will find next available port if 3000 is busy
    host: true,
    allowedHosts: [
      ".manuspre.computer",
      ".manus.computer",
      ".manus-asia.computer",
      ".manuscomputer.ai",
      ".manusvm.computer",
      "localhost",
      "127.0.0.1",
    ],
    fs: {
      strict: true,
      deny: ["**/.*"],
    },
  },
});
