import { Link } from "wouter";
import { COVERAGE_MAP_SVG, COVERAGE_SUBURBS, COVERAGE_SUBURB_COUNT } from "./coverageMapData";

/**
 * Service-area coverage map.
 *
 * Renders an inline SVG — no Google Maps SDK, no API key, no network request.
 * The Maps JavaScript API is not loaded anywhere on this site (the existing
 * GoogleMap component is a plain iframe embed), so a component calling
 * `new google.maps.Map()` renders nothing at all.
 *
 * The SVG and the suburb list are generated by scripts/generate-coverage-map.mjs
 * from client/src/suburbsData.ts, and the identical markup is injected into
 * client/index.html. Both layers therefore show the same map and the same links.
 * That parity is the point: a map only React can see contributes nothing to
 * local ranking, because the ranking value is in the crawlable linked list of
 * served suburbs, not in the picture.
 */
export default function CoverageMap() {
  return (
    <section
      id="coverage-map"
      className="py-24 bg-[#060607] border-t border-white/[0.06]"
      aria-labelledby="coverage-map-heading"
    >
      <div className="container">
        <div className="max-w-2xl mb-10">
          <span className="text-[#D0A050] font-semibold text-sm tracking-widest uppercase mb-3 block">
            Service Coverage
          </span>
          <h2
            id="coverage-map-heading"
            className="text-3xl sm:text-4xl lg:text-5xl font-bold text-[#EDEDEF] leading-tight mb-5"
            style={{ fontFamily: "Georgia, 'Times New Roman', serif" }}
          >
            Where we work
          </h2>
          <p className="text-[#B4B4B8] text-lg leading-relaxed">
            Based in Mordialloc, we cover {COVERAGE_SUBURB_COUNT} Melbourne suburbs across Bayside,
            Kingston, Glen Eira, Stonnington, the inner east, the southeast and the Mornington
            Peninsula. The rings mark 15, 30 and 45 kilometres from our base.
          </p>
        </div>

        <div
          className="rounded-xl overflow-hidden border border-white/[0.06] mb-10"
          // Generated at build time from our own data — never user input.
          dangerouslySetInnerHTML={{ __html: COVERAGE_MAP_SVG }}
        />

        <h3 className="text-xl font-bold text-[#EDEDEF] mb-4">Every suburb we service</h3>
        <ul className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-x-6 gap-y-2 mb-8">
          {COVERAGE_SUBURBS.map((s) => (
            <li key={s.href}>
              <Link
                href={s.href}
                className="text-[#B4B4B8] hover:text-[#D0A050] transition-colors text-sm"
              >
                {s.name}
              </Link>
            </li>
          ))}
        </ul>

        <p className="text-[#8B8B90] text-sm">
          Not listed? We travel beyond these suburbs regularly — call Jimmy on{" "}
          <a href="tel:0432077782" className="text-[#D0A050] hover:underline">
            0432 077 782
          </a>{" "}
          and ask.
        </p>
      </div>
    </section>
  );
}
